# DO NOT CHANGE
# The version of this configuration file.
# This is primarily used to apply automatic updates to the configuration file.
version: 0.8.0

###############################################################################
# RPG Attribute Settings                                                      #
###############################################################################
attribute: []

###############################################################################
# RPG Enchantment Settings                                                    #
###############################################################################
enchantment: []

###############################################################################
# RPG Potion Settings                                                         #
###############################################################################
potion:
  # The number of ticks between custom potion ticks.
  rate: 20
  
###############################################################################
# RPG Skill Settings                                                          #
###############################################################################
skill: []